wandb_version: 1

IPC:
  desc: null
  value: null
LOG_DIR:
  desc: null
  value: ../logs
_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.10
    t:
      1:
      - 1
      2:
      - 1
      - 5
      4: 3.8.10
      5: 0.10.32
      8:
      - 2
      - 5
alpha:
  desc: null
  value: 32
auxiliary_loss:
  desc: null
  value: 0
backbone_model:
  desc: null
  value: resnet50
bn_freeze:
  desc: null
  value: 0
crop:
  desc: null
  value: 224
dataset:
  desc: null
  value: cub
gd_config:
  desc: null
  value: M
gpu_id:
  desc: null
  value: 2
l2_norm:
  desc: null
  value: 1
loss:
  desc: null
  value: Proxy_Anchor
loss_lambda:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.001
lr_decay_gamma:
  desc: null
  value: 0.5
lr_decay_step:
  desc: null
  value: 5
model:
  desc: null
  value: cgdolg5
mrg:
  desc: null
  value: 0.1
nb_epochs:
  desc: null
  value: 35
nb_workers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: sgd
remark:
  desc: null
  value: M-lambda1-l2norm-nonaux
resize:
  desc: null
  value: 256
smoothing:
  desc: null
  value: 0.1
sz_batch:
  desc: null
  value: 120
sz_embedding:
  desc: null
  value: 512
temperature:
  desc: null
  value: 0.5
warm:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0001
